# https://raw.githubusercontent.com/daattali/beautiful-jekyll/master/_config.yml
title: "my site"
author: "someone"
description: "my site indeed "

colors:
  # Default colors
  primary:
    background: '0x000000'
    foreground: '0xc5c8c6'
