# https://raw.githubusercontent.com/daattali/beautiful-jekyll/master/_config.yml
title: "Test Title"
author: "Test AUthor"
description: "Test desc"

colors:
  # Default colors
  primary:
    background: '0x000000'
    foreground: '0xc5c8c6'
